version: '2'
services:
  db:
    image: postgres
  api:
    build:
      context: ./companies_organization_chart_api
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./companies_organization_chart_api:/companies_organization_chart_api
    ports:
      - "3000:3000"
    depends_on:
      - db
