development: &default
  adapter: postgresql
  encoding: unicode
  database: companies_organization_chart_api_development
  pool: 5
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: companies_organization_chart_test
